Mirupio
GDSC-Hongik/2024-1-Project-Track-BE pull request #26
Opened 2024-06-23 16:16 UTC by mirupio

## 📌 학습 진행 상황  Django 모델 파헤치기를 공부했다

## 🔗 WIL  https://leeward-rutabaga-82c.notion.site/7-Django-4e7f31ce01d1476c85ba924a34ccabc3?pvs=4

## 🫠 어려웠던 점, 보완해야 할 점  코드랑 외워야되는 형식이 너무 방대해서 공부하기 어렵다.

## 📚 앞으로의 계획  프로젝트에서 앱 구현할 때 필요한 기능들을 중점적으로 공부해야겠다.

2024-06-24 12:09 UTC, yeeunli requested changes
학습하신 것 정리하시느라 수고많으셨어요~
다만 폴더 구조 변경 아래 예시처럼 부탁드려요!
깃허브 닉네임이 최상단 폴더가 될 수 있도록 수정해주세요!

```
├─ Mirupio //깃허브 닉네임으로 설정
│     │
│     ├─ Round1 (dir)
│     │     │
│     │     ├─  Django 웹 개발 시작하기 //학습 주차에 맞는 토픽 주제로 작성
│     │     │    ├─ 실습1.js //되도록 강의 제목으로 코드 작성
│     │     │    ├─ 정리.md //배운 내용을 md 파일에 정리해도 GOOD! 
│     │     │    ├─ 실습2.js
│     │     │    ├─ ...
│     │     ├─  Django CRUD
│     │     │    ├─ 정리2.md
│     │     │    ├─ 실습3.js
│     │     │    ├─ ...
│     │     ├─ .. 이하동일
│     │
│     ├─ Round2
│     │     │
│     │     ├─  .. 이하동일
│     │
│     ├─ .. 이하 동일
│
```

2024-07-04 14:49 UTC, yeeunli commented
정하님, 폴더 수정 잘 해주셨네요~ 
다만, 지금 파일 변경 내역 보시면, 정하님 작업물 외에 다른 분들 작업물이 삭제되었다고 뜨거든요~ 이 상태에서 main으로 merge하면, 다른 분들 작업 내용이 삭제되어서요 🥲 
우선, 해당 PR은 닫을테니 main 브랜치를 다시 pull 해온 뒤에, 다른 분들 코드 삭제하지 마시고, 정하님 폴더 내용만 수정해서 다시 올려주세요!

2024-07-05 07:16 UTC, mirupio commented
헉 ㅠㅠ 죄송해요 
제가 깃을 잘 몰라서 찾아보면서 하는데도 자꾸 헷갈리네요..
그러면 git pull origin main하고 폴더 수정한 후 add, commit,push하면 되는거 맞나요..?! 🥹

-----Original Message-----
From: ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>; "State ***@***.***>;
Sent: 2024-07-04 (목) 23:49:38 (GMT+09:00)
Subject: Re: [GDSC-Hongik/2024-1-Project-Track-BE] Mirupio (PR #26)

정하님, 폴더 수정 잘 해주셨네요~
다만, 지금 파일 변경 내역 보시면, 정하님 작업물 외에 다른 분들 작업물이 삭제되었다고 뜨거든요~ 이 상태에서 main으로 merge하면, 다른 분들 작업 내용이 삭제되어서요 🥲
우선, 해당 PR은 닫을테니 main 브랜치를 다시 pull 해온 뒤에, 다른 분들 코드 삭제하지 마시고, 정하님 폴더 내용만 수정해서 다시 올려주세요!
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

2024-07-05 07:21 UTC, yeeunli commented
아니에요 정하님 ~~ 이렇게 알아가는거죠 ㅎㅎ 
네, 적어주신대로 진행하시면 돼요! 
또 궁금한 것 있으시면 언제든지 물어봐주세요 ☺️

2024-07-15 05:33 UTC, yeeunli commented
이 pr은 닫을테니, pr 새로 올려주세요~!

2024-07-15 05:33 UTC, closed without merging